module.exports = {
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        'accent-1': '#FAFAFA',
        'accent-2': '#EAEAEA',
        'accent-7': '#333',
        info: '#0070f3',
        cyan: {
          100: '#d9f7f3',
          200: '#b2eee6',
          300: '#8ce6da',
          400: '#65ddcd',
          500: '#3fd5c1',
          600: '#32aa9a',
          700: '#268074',
          800: '#19554d',
          900: '#0d2b27',
        },
        fuchsia: {
          100: '#ffd9f7',
          200: '#ffb2ee',
          300: '#ff8ce6',
          400: '#ff65dd',
          500: '#ff3fd5',
          600: '#cc32aa',
          700: '#992680',
          800: '#661955',
          900: '#330d2b',
        },
      },
      spacing: {
        28: '7rem',
      },
      lineHeight: {
        tight: 1.2,
      },
      fontSize: {
        '5xl': '2.5rem',
        '6xl': '2.75rem',
        '7xl': '4.5rem',
        '8xl': '6.25rem',
      },
      boxShadow: {
        small: '0 5px 10px rgba(0, 0, 0, 0.12)',
        medium: '0 8px 30px rgba(0, 0, 0, 0.12)',
      },
    },
  },
  variants: {
    // appearance: [],
    // can help remove utility classes
    // save most size by limiting color palette and breakpoints
  },
  plugins: [],
  purge: ['./pages/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
}

// Default configuration
// module.exports = {
//   // ...
//   variants: {
//     accessibility: ['responsive', 'focus'],
//     alignContent: ['responsive'],
//     alignItems: ['responsive'],
//     alignSelf: ['responsive'],
//     appearance: ['responsive'],
//     backgroundAttachment: ['responsive'],
//     backgroundClip: ['responsive'],
//     backgroundColor: ['responsive', 'hover', 'focus'],
//     backgroundImage: ['responsive'],
//     gradientColorStops: ['responsive', 'hover', 'focus'],
//     backgroundOpacity: ['responsive', 'hover', 'focus'],
//     backgroundPosition: ['responsive'],
//     backgroundRepeat: ['responsive'],
//     backgroundSize: ['responsive'],
//     borderCollapse: ['responsive'],
//     borderColor: ['responsive', 'hover', 'focus'],
//     borderOpacity: ['responsive', 'hover', 'focus'],
//     borderRadius: ['responsive'],
//     borderStyle: ['responsive'],
//     borderWidth: ['responsive'],
//     boxShadow: ['responsive', 'hover', 'focus'],
//     boxSizing: ['responsive'],
//     container: ['responsive'],
//     cursor: ['responsive'],
//     display: ['responsive'],
//     divideColor: ['responsive'],
//     divideOpacity: ['responsive'],
//     divideStyle: ['responsive'],
//     divideWidth: ['responsive'],
//     fill: ['responsive'],
//     flex: ['responsive'],
//     flexDirection: ['responsive'],
//     flexGrow: ['responsive'],
//     flexShrink: ['responsive'],
//     flexWrap: ['responsive'],
//     float: ['responsive'],
//     clear: ['responsive'],
//     fontFamily: ['responsive'],
//     fontSize: ['responsive'],
//     fontSmoothing: ['responsive'],
//     fontStyle: ['responsive'],
//     fontWeight: ['responsive', 'hover', 'focus'],
//     height: ['responsive'],
//     inset: ['responsive'],
//     justifyContent: ['responsive'],
//     letterSpacing: ['responsive'],
//     lineHeight: ['responsive'],
//     listStylePosition: ['responsive'],
//     listStyleType: ['responsive'],
//     margin: ['responsive'],
//     maxHeight: ['responsive'],
//     maxWidth: ['responsive'],
//     minHeight: ['responsive'],
//     minWidth: ['responsive'],
//     objectFit: ['responsive'],
//     objectPosition: ['responsive'],
//     opacity: ['responsive', 'hover', 'focus'],
//     order: ['responsive'],
//     outline: ['responsive', 'focus'],
//     overflow: ['responsive'],
//     overscrollBehavior: ['responsive'],
//     padding: ['responsive'],
//     placeholderColor: ['responsive', 'focus'],
//     placeholderOpacity: ['responsive', 'focus'],
//     pointerEvents: ['responsive'],
//     position: ['responsive'],
//     resize: ['responsive'],
//     space: ['responsive'],
//     stroke: ['responsive'],
//     strokeWidth: ['responsive'],
//     tableLayout: ['responsive'],
//     textAlign: ['responsive'],
//     textColor: ['responsive', 'hover', 'focus'],
//     textOpacity: ['responsive', 'hover', 'focus'],
//     textDecoration: ['responsive', 'hover', 'focus'],
//     textTransform: ['responsive'],
//     userSelect: ['responsive'],
//     verticalAlign: ['responsive'],
//     visibility: ['responsive'],
//     whitespace: ['responsive'],
//     width: ['responsive'],
//     wordBreak: ['responsive'],
//     zIndex: ['responsive'],
//     gap: ['responsive'],
//     gridAutoFlow: ['responsive'],
//     gridTemplateColumns: ['responsive'],
//     gridColumn: ['responsive'],
//     gridColumnStart: ['responsive'],
//     gridColumnEnd: ['responsive'],
//     gridTemplateRows: ['responsive'],
//     gridRow: ['responsive'],
//     gridRowStart: ['responsive'],
//     gridRowEnd: ['responsive'],
//     transform: ['responsive'],
//     transformOrigin: ['responsive'],
//     scale: ['responsive', 'hover', 'focus'],
//     rotate: ['responsive', 'hover', 'focus'],
//     translate: ['responsive', 'hover', 'focus'],
//     skew: ['responsive', 'hover', 'focus'],
//     transitionProperty: ['responsive'],
//     transitionTimingFunction: ['responsive'],
//     transitionDuration: ['responsive'],
//     transitionDelay: ['responsive'],
//     animation: ['responsive']
//   }
// }
